# Crowdin configuration file
# see: https://support.crowdin.com/configuration-file/
#
# you will need the CLI client
# see: https://support.crowdin.com/cli-tool/
#
# Crowdin supports a lot of files: https://support.crowdin.com/supported-formats/
#

project_identifier: qownnotes
project_id: 158883

# the api token has to be provided by ~/.crowdin.yaml
# generate a personal token on https://crowdin.com/settings#api-key
#api_token: XXXX

preserve_hierarchy: true
files:
  -
    # source files filter
    source: '/src/languages/QOwnNotes_en.ts'
    # where translations live
    translation: '/src/languages/QOwnNotes_%locale_with_underscore%.ts'
    #translation: '/src/languages/QOwnNotes_%locale%.ts'
    #translation: 'src/languages/QOwnNotes_%two_letters_code%.ts'
    #"languages_mapping" : {
      #"two_letters_code" : {
        #"pt" : "pt_PT",
        #"pt-BR" : "pt_BR"
      #}
    #}
    dest: '/QOwnNotes_en.ts'
    "languages_mapping" : {
      "locale_with_underscore" : {
        "ar_SA" : "ar",
        "ca_ES" : "ca",
        "cs_CZ" : "cs",
        "de_DE" : "de",
        "es_ES" : "es",
        "fr_FR" : "fr",
        "hr_HR" : "hr",
        "hu_HU" : "hu",
        "sv_SE" : "sv",
        "it_IT" : "it",
        "ja_JP" : "ja",
        "nl_NL" : "nl",
        "pl_PL" : "pl",
        "ru_RU" : "ru",
        "uk_UA" : "uk",
        "id_ID" : "id",
        "bn_BD" : "bn",
        "tr_TR" : "tr",
        "tl_PH" : "tl",
        "fil_PH" : "fil",
        "ceb_PH" : "ceb",
        "hi_IN" : "hi",
        "gl_ES" : "gl",
        "no_NO" : "no",
        "no_DK" : "da",
        "ro_RO" : "ro",
        "sk_SK" : "sk",
        "sl_SI" : "sl",
        "eu_ES" : "eu",
        "sr_SP" : "sr",
        "fa_IR" : "fa",
        "bg_BG" : "bg",
        "is_IS" : "is",
        "pa_IN" : "pa",
        "sq_AL" : "sq",
        "he_IL" : "he",
        "yi_DE" : "yi",
        "th_TH" : "th",
        "sn_ZW" : "sn",
        "km_KH" : "km",
        "si_LK" : "si",
        "zu_ZA" : "zu",
        "xh_ZA" : "xh",
        "ms_MY" : "ms",
        "mi_NZ" : "mi",
        "ga_IE" : "ga",
        "uz_UZ" : "uz",
        "vi_VN" : "vi",
        "lv_LV" : "vl",
        "ku_TR" : "ku",
        "lt_LT" : "lt",
        "bs_BA" : "bs",
        "mk_MK" : "mk",
        "ko_KR" : "ko",
        "et_EE" : "et",
      }
    }
  -
    source: '/webpage/src/index.md'
    translation: '/webpage/src/%two_letters_code%/%original_file_name%'
  -
    source: '/webpage/src/contributing/*.md'
    translation: '/webpage/src/%two_letters_code%/contributing/%original_file_name%'
  -
    source: '/webpage/src/editor/*.md'
    translation: '/webpage/src/%two_letters_code%/editor/%original_file_name%'
  -
    source: '/webpage/src/faq/*.md'
    translation: '/webpage/src/%two_letters_code%/faq/%original_file_name%'
  -
    source: '/webpage/src/getting-started/*.md'
    translation: '/webpage/src/%two_letters_code%/getting-started/%original_file_name%'
  -
    source: '/webpage/src/installation/*.md'
    translation: '/webpage/src/%two_letters_code%/installation/%original_file_name%'
  -
    source: '/webpage/src/scripting/*.md'
    translation: '/webpage/src/%two_letters_code%/scripting/%original_file_name%'
