name: Build QOwnNotes

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Linux:   https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/
        # macOS:   https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/
        # Windows: https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/
        qt-version: ['5.3', '5.4', '5.7', '5.13.2', '5.14.2', '5.15.1']
        experimental: [false]
        exclude:
          # xcode not found
          - os: macos-latest
            qt-version: '5.3'
          # xcode not found
          - os: macos-latest
            qt-version: '5.4'
          # win64_mingw73 not found
          - os: windows-latest
            qt-version: '5.3'
          # win64_mingw73 not found
          - os: windows-latest
            qt-version: '5.4'
          # Qt installation times out too often
#          - os: windows-latest
#            qt-version: '5.13.2'
          # win64_mingw73 not found
#          - os: windows-latest
#            qt-version: '5.15.0'
#          # qt.conf not found (https://github.com/jurplel/install-qt-action/issues/54)
#          - os: windows-latest
#            qt-version: '5.15.1'
          # botan 32bit error
          - os: windows-latest
            qt-version: '5.7'
#        include:
#          - os: ubuntu-latest
#            qt-version: '6.0.0'
#            experimental: true
#          - os: macos-latest
#            qt-version: '6.0.0'
#            experimental: true
#          - os: windows-latest
#            qt-version: '6.0.0'
#            experimental: true
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - id: files
      uses: jitterbit/get-changed-files@v1
    - id: changes
      name: Check if we want to build QOwnNotes
      shell: bash
      run: |
        unset DO_BUILD
        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ ${changed_file} = src* ]] || [[ ${changed_file} = ".github/workflows/build-test.yml" ]] ;
          then
            echo "'${changed_file}' matches, we will build"
            DO_BUILD='true'
          fi
        done
        echo "DO_BUILD: ${DO_BUILD}"
        echo ::set-output name=DO_BUILD::${DO_BUILD}

      #
      # Install Qt
      #

    - if: steps.changes.outputs.DO_BUILD
      name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}
    # https://github.com/jurplel/install-qt-action
    - if: contains( matrix.os, 'windows') && ( matrix.qt-version == '5.7' ) && steps.changes.outputs.DO_BUILD
      name: Install Qt 5.7 on Windows
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        arch: win32_mingw53
        # try mirror
#        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        aqtversion: '==0.9.4'
#        py7zrversion: '==0.9.0'
    - if: contains( matrix.os, 'windows') && ( matrix.qt-version == '5.15.1' ) && steps.changes.outputs.DO_BUILD
      name: Install Qt 5.15.1 on Windows
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        arch: win64_mingw81
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - if: contains( matrix.os, 'windows') && ( matrix.qt-version != '5.7' ) && ( matrix.qt-version != '5.15.1' ) && steps.changes.outputs.DO_BUILD
      name: Install Qt on Windows
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        arch: win64_mingw73
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - if: false == contains( matrix.os, 'windows') && steps.changes.outputs.DO_BUILD
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

      #
      # Do tests
      #

    - if: contains( matrix.os, 'ubuntu') && ( matrix.qt-version != '5.3' ) && ( matrix.qt-version != '5.4' ) && ( matrix.qt-version != '5.7' ) && steps.changes.outputs.DO_BUILD
      name: Do Linux tests
      run: |
        cd ../tests && qmake DEFINES+=INTEGRATION_TESTS && make -s -j 2
        ../bin/tests/tests -platform minimal -txt
    - if: contains( matrix.os, 'macos') && steps.changes.outputs.DO_BUILD
      name: Do macOS tests
      run: |
        cd ../tests && qmake DEFINES+=INTEGRATION_TESTS && make -s -j 2
        ../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
    - if: contains( matrix.os, 'windows') && steps.changes.outputs.DO_BUILD
      name: Do Windows tests
      run: |
        cd ..\tests
        qmake DEFINES+=INTEGRATION_TESTS
        make
        copy ..\build-systems\github\windows\libcrypto-1_1-x64.dll .
        copy ..\build-systems\github\windows\libssl-1_1-x64.dll .
        copy ..\bin\tests\tests.exe .
        windeployqt tests.exe
        .\tests.exe -txt

      #
      # Build QOwnNotes
      #

    - if: steps.changes.outputs.DO_BUILD
      name: Build QOwnNotes
      run: |
        lrelease QOwnNotes.pro && qmake && make
